
TEX_CHOICE = "Warcraft Classic"
TEX_HEIGHT = 340
UI_WIDTH = 1365.33342670471
TEX_ALPHA = 1
TEX_WIDTH = 800
TEX_X = 0
TEX_Y = 0
TEX_STRATA = "BACKGROUND"
TEX_VERTEX_R = "1"
TEX_VERTEX_G = "1"
TEX_VERTEX_B = "1"
TEX_VIEWPORT_BL = 0
TEX_VIEWPORT_BR = 0
TEX_VIEWPORT_TL = 0
TEX_VIEWPORT_TR = 0
TEX_CHAT = 0
